trigger: none

pool:
  vmImage: ubuntu-latest

variables:
- group: cloudfrontS3DemoGroupSecure
- group: cloudfrontS3DemoGroupNormal


stages:
  - stage: ProvisionAWSInfrastructure
    displayName: "Deploy CFT Stack for S3/CloudFront to Maolte Sandbox"
    jobs:
    - job:
      steps:
      - task: CloudFormationCreateOrUpdateStack@1
        inputs:
          awsCredentials: $env:AWS_ACCCESS_CREDS
          regionName: $env:awsRegion
          stackName: $env:cftStackName
          templateFile: 'iac/provision-infrastructure.yaml'
          captureStackOutputs: asVariables
        env:
          AWS_ACCCESS_CREDS: $(awsAccessKey)    
  - stage: UploadFilesToS3
    dependsOn: ProvisionAWSInfrastructure
    displayName: "Deploy Static (S3) Site"
    jobs:
    - job:
      steps:
      - task: S3Upload@1
        displayName: "Upload static site files to newly created S3"
        inputs:
          awsCredentials: $env:AWS_ACCCESS_CREDS
          regionName: $env:awsRegion
          bucketName: $(S3BucketName)
          sourceFolder: '$(System.DefaultWorkingDirectory)/code'
          globExpressions: '**'
          filesAcl: 'bucket-owner-full-control'
        env:
          AWS_ACCCESS_CREDS: $(awsAccessKey)   
        



