trigger: none

pool:
  vmImage: ubuntu-latest

parameters:
  - name: RegionCode
    type: string 
    default: 'eu-west-1'
  - name: CFTStackName
    type: string
    default: 'CloudFrontS3DemoStack'

stages:
  - stage: ProvisionAWSInfrastructure
    displayName: "Deploy CFT Stack for S3/CloudFront to Maolte Sandbox"
    jobs:
    - job:
      steps:
      - task: CloudFormationCreateOrUpdateStack@1
        inputs:
          awsCredentials: 'cloudfrontDemoSandbox'
          regionName: ${{ parameters.RegionCode }}
          stackName: ${{ parameters.CFTStackName }}
          templateFile: 'iac/provision-infrastructure.yaml'
          templateParametersFile: 'iac/params.json'
          captureStackOutputs: asVariables
      - bash:
          echo "Declaring the captured S3 bucket values from output CFT outputs:"
          echo "##vso[task.setvariable variable=S3BucketNameVar;isOutput=true] $S3BucketName"
        name: DeclareS3BucketVar    
      - script:
          echo "Found the following:"
          echo "$(S3BucketNameVar)"
        name: PrintS3OutputsFromCFT  


  - stage: UploadFilesToS3
    dependsOn: ProvisionAWSInfrastructure
    displayName: "Deploy Static (S3) Site"
    jobs:
    - job:
      steps:
      - task: S3Upload@1
        displayName: "Upload static site files to newly created S3"
        inputs:
          awsCredentials: 'cloudfrontDemoSandbox'
          regionName: ${{ parameters.RegionCode }}
          bucketName: '$(S3BucketNameVar)'
          sourceFolder: '$(System.DefaultWorkingDirectory)/code'
          globExpressions: '**'
          filesAcl: 'bucket-owner-full-control'
        



