trigger: none

pool:
  vmImage: ubuntu-latest

parameters:
  - name: RegionCode
    type: string 
    default: 'eu-west-1'
  - name: CFTStackName
    type: string
    default: 'CloudFrontS3DemoStack'

variables:
  - name: S3BucketNameVar
    value: 'var-initialised'

stages:
  - stage: ProvisionAWSInfrastructure
    displayName: "Deploy CFT Stack for S3/CloudFront to Maolte Sandbox"
    jobs:
    - job:
      steps:
      - task: CloudFormationCreateOrUpdateStack@1
        inputs:
          awsCredentials: 'cloudfrontDemoSandbox'
          regionName: ${{ parameters.RegionCode }}
          stackName: ${{ parameters.CFTStackName }}
          templateFile: 'iac/provision-infrastructure.yaml'
          templateParametersFile: 'iac/params.json'
          captureStackOutputs: asVariables
      - script: |
          echo "##vso[task.setvariable variable=S3BucketNameVar;isOutput=true] $S3BucketName" 
        name: setS3BucketName 
        displayName: "CFT Stack Var Been Declared for next Stage for S3 Bucket"
      - script:
          echo "Found the following:"
          echo $(setS3BucketName.S3BucketNameVar)
          echo $env:S3BucketName
        name: PrintS3OutputsFromCFT


  - stage: UploadFilesToS3
    dependsOn: ProvisionAWSInfrastructure
    displayName: "Deploy Static (S3) Site"
    jobs:
    - job:
      steps:
      - task: S3Upload@1
        displayName: "Upload static site files to newly created S3"
        inputs:
          awsCredentials: 'cloudfrontDemoSandbox'
          regionName: ${{ parameters.RegionCode }}
          bucketName: '$(S3BucketNameVar)'
          sourceFolder: '$(System.DefaultWorkingDirectory)/code'
          globExpressions: '**'
          filesAcl: 'bucket-owner-full-control'
        



