trigger: none

pool:
  vmImage: ubuntu-latest

parameters:
  - name: RegionCode
    type: string 
    default: 'eu-west-1'
  - name: CFTStackName
    type: string
    default: 'CloudFrontS3DemoStack'
  - name: AWSServiceConn
    type: string
    default: 'cloudfrontDemoSandbox'

stages:
  - stage: ProvisionAWSInfrastructure
    displayName: "Deploy CFT Stack for S3/CloudFront to Maolte Sandbox"
    jobs:
    - job: ExecuteInfraTemplate
      steps:
      - task: CloudFormationCreateOrUpdateStack@1
        inputs:
          awsCredentials: ${{ parameters.AWSServiceConn }}
          regionName: ${{ parameters.RegionCode }}
          stackName: ${{ parameters.CFTStackName }}
          templateFile: 'iac/provision-infrastructure.yaml'
          templateParametersFile: 'iac/params.json'
          captureStackOutputs: asVariables
      - bash: echo "##vso[task.setvariable variable=cftS3BucketOutput;isOutput=true] $S3BUCKET_NAME"
        env:
          S3BUCKET_NAME: $(S3BucketName)
        name: declareCFTOutputs
      - bash: |
          echo '$(declareCFTOutputs.cftS3BucketOutput)'
          echo '$(S3BucketName)'
          echo '$S3BUCKET_NAME'
          echo '$(CfDistributionDomainName)'
          echo 'Write-Host "Captured S3 Bucket var: $(cftS3BucketOutput)"'
        name: echoCFTOutputs

  - stage: UploadFilesToS3
    dependsOn: ProvisionAWSInfrastructure
    displayName: "Deploy Static (S3) Site"
    jobs:
    - job: UploadStaticSiteFiles
      variables:
        s3BucketLocalVar: $[stageDependencies.ProvisionAWSInfrastructure.ExecuteInfraTemplate.outputs['declareCFTOutputs.cftS3BucketOutput']]
      steps:
      - bash: |
          echo "S3 Local Variables: "
          echo $(s3BucketLocalVar)
        name: S3StageVariableChecks
      - task: S3Upload@1
        displayName: "Upload static site files to newly created S3"
        inputs:
          awsCredentials: ${{ parameters.AWSServiceConn }}
          regionName: ${{ parameters.RegionCode }}
          bucketName: $(s3BucketLocalVar)
          sourceFolder: '$(System.DefaultWorkingDirectory)/code'
          globExpressions: '**'
          filesAcl: 'bucket-owner-full-control'
        



