trigger: none

pool:
  vmImage: ubuntu-latest

variables:
- group: cloudfrontS3DemoGroupSecure
- template: vars.yaml

parameters:
  - name: AWSRegion
    type: string
    default: $(awsRegion)
  - name: DesignatedStackName
    type: string
    default: $(cftStackName)
  - name: AWSAccessCreds
    type: string
    default: $(awsAccessKey)


stages:
  - stage: ProvisionAWSInfrastructure
    displayName: "Deploy CFT Stack for S3/CloudFront to Maolte Sandbox"
    jobs:
    - job:
      steps:
      - task: CloudFormationCreateOrUpdateStack@1
        inputs:
          awsCredentials: ${{ parameters.AWSAccessCreds }}
          regionName: ${{ parameters.AWSRegion }}
          stackName: ${{ parameters.DesignatedStackName }}
          templateFile: 'iac/provision-infrastructure.yaml'
          captureStackOutputs: asVariables     
  - stage: UploadFilesToS3
    dependsOn: ProvisionAWSInfrastructure
    displayName: "Deploy Static (S3) Site"
    jobs:
    - job:
      steps:
      - task: S3Upload@1
        displayName: "Upload static site files to newly created S3"
        inputs:
          awsCredentials: ${{ parameters.AWSAccessCreds }}
          regionName: ${{ parameters.AWSRegion }}
          bucketName: $(S3BucketName)
          sourceFolder: '$(System.DefaultWorkingDirectory)/code'
          globExpressions: '**'
          filesAcl: 'bucket-owner-full-control'
        



