trigger: none

pool:
  vmImage: ubuntu-latest

variables:
  - group: 'cloudfrontS3DemoGroupSecure'
  - group: 'cloudfrontS3DemoGroupNormal'

parameters:
  - name: AWSAccessCreds
    type: string 
    default: 'us-east-1'
stages:
  - stage: ProvisionAWSInfrastructure
    displayName: "Deploy CFT Stack for S3/CloudFront to Maolte Sandbox"
    jobs:
    - job:
      steps:
      - task: CloudFormationCreateOrUpdateStack@1
        inputs:
          awsCredentials: 'cloudfrontDemoSandbox'
          regionName: 'eu-west-1'
          stackName: $[variables.awsAccessKey]
          templateFile: 'iac/provision-infrastructure.yaml'
          captureStackOutputs: asVariables

  - stage: UploadFilesToS3
    dependsOn: ProvisionAWSInfrastructure
    displayName: "Deploy Static (S3) Site"
    jobs:
    - job:
      steps:
      - task: S3Upload@1
        displayName: "Upload static site files to newly created S3"
        inputs:
          awsCredentials: 'cloudfrontDemoSandbox'
          regionName: ${{ parameters.AWSAccessCreds }}
          bucketName: $(S3BucketName)
          sourceFolder: '$(System.DefaultWorkingDirectory)/code'
          globExpressions: '**'
          filesAcl: 'bucket-owner-full-control'
        



