trigger: none

pool:
  vmImage: ubuntu-latest

variables:
- group: cloudfrontS3DemoGroupSecure

parameters:
  - name: AWSRegion
    type: string
    default: 'eu-east-1'
  - name: DesignatedStackName
    type: string
    default: 'DemoCloudFrontS3Stack'



stages:
  - stage: ProvisionAWSInfrastructure
    displayName: "Deploy CloudFormation IAC Stack for S3/CloudFront to Maolte Sandbox"
    jobs:
    - job:
      steps:
      - task: CloudFormationCreateOrUpdateStack@1
        inputs:
          awsCredentials: $(awsAccessKey)
          regionName: ${{ parameters.AWSRegion }}
          stackName: ${{ parameters.DesignatedStackName }}
          templateFile: 'iac/provision-infrastructure.yaml'
          captureStackOutputs: asVariables

        
  - stage: UploadFilesToS3
    dependsOn: ProvisionAWSInfrastructure
    jobs:
    - job:
      steps:
      - task: S3Upload@1
        displayName: "Upload static site files to newly created S3"
        inputs:
          awsCredentials: '$(awsAccessKey)'
          regionName: '${{ parameters.AWSRegion }}'
          bucketName: '$(S3BucketName)'
          sourceFolder: '$(System.DefaultWorkingDirectory)/code'
          globExpressions: '**'
          filesAcl: 'bucket-owner-full-control'
        



